import { Router, type IRouter } from "express";
import healthRouter from "./health";
import searchRouter from "./search";
import instagramRouter from "./instagram";
import storageRouter from "./storage";
import craftAssistantRouter from "./craft-assistant";
import aiCaptionRouter from "./ai-caption";
import aiEnhanceRouter from "./ai-enhance";
import stripeRouter from "./stripe";
import stripeConnectRouter from "./stripe-connect";
import glazeOracleRouter from "./glaze-oracle";
import grantWriterRouter from "./grant-writer";
import authRouter from "./auth";
import feedRouter from "./feed";
import postsRouter from "./posts";
import socialRouter from "./social";
import notificationsRouter from "./notifications";
import messagesRouter from "./messages";
import shopRouter from "./shop";
import workshopsRouter from "./workshops";
import commissionsRouter from "./commissions";
import guildsRouter from "./guilds";
import dropsRouter from "./drops";
import auctionsRouter from "./auctions";
import patronsRouter from "./patrons";
import discoverRouter from "./discover";
import storiesRouter from "./stories";
import tipsRouter from "./tips";
import reviewsRouter from "./reviews";
import campaignsRouter from "./campaigns";
import broadcastsRouter from "./broadcasts";
import resaleRouter from "./resale";
import boostsRouter from "./boosts";
import linkInBioRouter from "./link-in-bio";
import subscriptionBoxesRouter from "./subscription-boxes";
import meRouter from "./me";
import streaksRouter from "./streaks";
import badgesRouter from "./badges";
import challengesRouter from "./challenges";
import referralsRouter from "./referrals";
import pollsRouter from "./polls";
import ghostModeRouter from "./ghost-mode";
import glazeLibraryRouter from "./glaze-library";
import inspirationBoardsRouter from "./inspiration-boards";
import craftCalendarRouter from "./craft-calendar";
import materialExchangeRouter from "./material-exchange";
import communityEventsRouter from "./community-events";
import beatsRouter from "./beats";
import userSettingsRouter from "./user-settings";
import serverCartRouter from "./server-cart";
import digitalDownloadsRouter from "./digital-downloads";
import collabBoardRouter from "./collab-board";
import kilnFiringsRouter from "./kiln-firings";
import craftHoursRouter from "./craft-hours";
import parliamentRouter from "./parliament";
import studioMapRouter from "./studio-map";
import trendingPostsRouter from "./trending-posts";
import userPaymentSettingsRouter from "./user-payment-settings";
import beatLicensesRouter from "./beat-licenses";
import collectorPortalRouter from "./collector-portal";
import opportunitySavesRouter from "./opportunity-saves";
import priceAlertsRouter from "./price-alerts";
import reportsRouter from "./reports";
import pushRouter from "./push";
import adminRouter from "./admin";
import analyticsRouter from "./analytics";
import giftCardsRouter from "./gift-cards";
import videoRouter from "./video";
import payoutsRouter from "./payouts";
import newslettersRouter from "./newsletters";
import mentorshipRouter from "./mentorship";
import critiquesRouter from "./critiques";
import foundingArtistRouter from "./founding-artist";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use("/instagram", instagramRouter);
router.use(storageRouter);
router.use(craftAssistantRouter);
router.use(aiCaptionRouter);
router.use(aiEnhanceRouter);
router.use(stripeRouter);
router.use(stripeConnectRouter);
router.use(glazeOracleRouter);
router.use(grantWriterRouter);
router.use(feedRouter);
router.use(postsRouter);
router.use(socialRouter);
router.use(notificationsRouter);
router.use(messagesRouter);
router.use(shopRouter);
router.use(workshopsRouter);
router.use(commissionsRouter);
router.use(guildsRouter);
router.use(dropsRouter);
router.use(auctionsRouter);
router.use(patronsRouter);
router.use(discoverRouter);
router.use(searchRouter);
router.use(storiesRouter);
router.use(tipsRouter);
router.use(reviewsRouter);
router.use(campaignsRouter);
router.use(broadcastsRouter);
router.use(resaleRouter);
router.use(boostsRouter);
router.use(linkInBioRouter);
router.use(subscriptionBoxesRouter);
router.use(meRouter);
router.use(streaksRouter);
router.use(badgesRouter);
router.use(challengesRouter);
router.use(referralsRouter);
router.use(pollsRouter);
router.use(ghostModeRouter);
router.use(glazeLibraryRouter);
router.use(inspirationBoardsRouter);
router.use(craftCalendarRouter);
router.use(materialExchangeRouter);
router.use(communityEventsRouter);
router.use(beatsRouter);
router.use(userSettingsRouter);
router.use(serverCartRouter);
router.use(digitalDownloadsRouter);
router.use(collabBoardRouter);
router.use(kilnFiringsRouter);
router.use(craftHoursRouter);
router.use(parliamentRouter);
router.use(studioMapRouter);
router.use(trendingPostsRouter);
router.use(userPaymentSettingsRouter);
router.use(beatLicensesRouter);
router.use(collectorPortalRouter);
router.use(opportunitySavesRouter);
router.use(priceAlertsRouter);
router.use(reportsRouter);
router.use(pushRouter);
router.use(adminRouter);
router.use(analyticsRouter);
router.use(giftCardsRouter);
router.use(videoRouter);
router.use(payoutsRouter);
router.use(newslettersRouter);
router.use(mentorshipRouter);
router.use(critiquesRouter);
router.use(foundingArtistRouter);

export default router;
