import { Router, type IRouter } from "express";
import healthRouter from "./health";
import searchRouter from "./search";
import instagramRouter from "./instagram";
import storageRouter from "./storage";
import craftAssistantRouter from "./craft-assistant";
import aiCaptionRouter from "./ai-caption";
import stripeRouter from "./stripe";
import glazeOracleRouter from "./glaze-oracle";
import grantWriterRouter from "./grant-writer";
import authRouter from "./auth";
import feedRouter from "./feed";
import postsRouter from "./posts";
import socialRouter from "./social";
import notificationsRouter from "./notifications";
import messagesRouter from "./messages";
import shopRouter from "./shop";
import workshopsRouter from "./workshops";
import commissionsRouter from "./commissions";
import guildsRouter from "./guilds";
import dropsRouter from "./drops";
import auctionsRouter from "./auctions";
import patronsRouter from "./patrons";
import discoverRouter from "./discover";
import storiesRouter from "./stories";
import tipsRouter from "./tips";
import reviewsRouter from "./reviews";
import campaignsRouter from "./campaigns";
import broadcastsRouter from "./broadcasts";
import resaleRouter from "./resale";
import boostsRouter from "./boosts";
import linkInBioRouter from "./link-in-bio";
import subscriptionBoxesRouter from "./subscription-boxes";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use("/instagram", instagramRouter);
router.use(storageRouter);
router.use(craftAssistantRouter);
router.use(aiCaptionRouter);
router.use(stripeRouter);
router.use(glazeOracleRouter);
router.use(grantWriterRouter);
router.use(feedRouter);
router.use(postsRouter);
router.use(socialRouter);
router.use(notificationsRouter);
router.use(messagesRouter);
router.use(shopRouter);
router.use(workshopsRouter);
router.use(commissionsRouter);
router.use(guildsRouter);
router.use(dropsRouter);
router.use(auctionsRouter);
router.use(patronsRouter);
router.use(discoverRouter);
router.use(searchRouter);
router.use(storiesRouter);
router.use(tipsRouter);
router.use(reviewsRouter);
router.use(campaignsRouter);
router.use(broadcastsRouter);
router.use(resaleRouter);
router.use(boostsRouter);
router.use(linkInBioRouter);
router.use(subscriptionBoxesRouter);

export default router;
