// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bg-remove/CharcoalBackground.tsx": () => import("../components/mockups/bg-remove/CharcoalBackground.tsx"),
  "./components/mockups/bg-remove/WhiteBackground.tsx": () => import("../components/mockups/bg-remove/WhiteBackground.tsx")
};
